// Command genwire generates the browser's TypeScript wire DTOs from the Go
// structs and string enums in wire_contract.go.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
)

var outputNames = map[string]string{
	"wireEventType":            "WireEventType",
	"wireDeltaKind":            "DeltaKind",
	"wireDeliveryMode":         "DeliveryMode",
	"wireFileChangeType":       "FileChangeType",
	"wireFailureChangeType":    "FailureChangeType",
	"wireFileOperation":        "FileOperation",
	"wireHunk":                 "Hunk",
	"wireFileChangePayload":    "FileChangePayload",
	"wireFailureChangePayload": "FailureChangePayload",
	"wireChange":               "Change",
	"wireImage":                "MessageImage",
	"wirePreview":              "PreviewRequest",
	"wireUsageCost":            "UsageCost",
	"wireUsage":                "Usage",
	"wireContextUsage":         "ContextUsage",
	"wireEvent":                "WireEvent",
	"wireHistoryResponse":      "HistoryResponse",
}

var outputOrder = []string{
	"wireEventType",
	"wireDeltaKind",
	"wireDeliveryMode",
	"wireFileChangeType",
	"wireFailureChangeType",
	"wireFileOperation",
	"wireHunk",
	"wireFileChangePayload",
	"wireFailureChangePayload",
	"wireChange",
	"wireImage",
	"wirePreview",
	"wireUsageCost",
	"wireUsage",
	"wireContextUsage",
	"wireEvent",
	"wireHistoryResponse",
}

type sourceType struct {
	expr ast.Expr
	doc  string
}

func main() {
	source := flag.String("source", "wire_contract.go", "Go source file containing the wire contract")
	output := flag.String("output", "-", "generated TypeScript file, or - for stdout")
	flag.Parse()

	generated, err := generate(*source)
	if err != nil {
		fmt.Fprintln(os.Stderr, "genwire:", err)
		os.Exit(1)
	}
	if *output == "-" {
		_, err = os.Stdout.Write(generated)
	} else {
		err = os.MkdirAll(filepath.Dir(*output), 0o755)
		if err == nil {
			err = os.WriteFile(*output, generated, 0o644)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "genwire:", err)
		os.Exit(1)
	}
}

func generate(source string) ([]byte, error) {
	file, err := parser.ParseFile(token.NewFileSet(), source, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	types := make(map[string]sourceType)
	constants := make(map[string][]string)
	for _, declaration := range file.Decls {
		decl, ok := declaration.(*ast.GenDecl)
		if !ok {
			continue
		}
		switch decl.Tok {
		case token.TYPE:
			for _, spec := range decl.Specs {
				typeSpec := spec.(*ast.TypeSpec)
				doc := commentText(typeSpec.Doc)
				if doc == "" {
					doc = commentText(decl.Doc)
				}
				types[typeSpec.Name.Name] = sourceType{expr: typeSpec.Type, doc: doc}
			}
		case token.CONST:
			for _, spec := range decl.Specs {
				valueSpec := spec.(*ast.ValueSpec)
				ident, ok := valueSpec.Type.(*ast.Ident)
				if !ok {
					continue
				}
				for _, value := range valueSpec.Values {
					literal, ok := value.(*ast.BasicLit)
					if !ok || literal.Kind != token.STRING {
						continue
					}
					decoded, err := strconv.Unquote(literal.Value)
					if err != nil {
						return nil, err
					}
					constants[ident.Name] = append(constants[ident.Name], decoded)
				}
			}
		}
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by go generate ./coding/internal/httpapi; DO NOT EDIT.\n\n")
	for _, goName := range outputOrder {
		sourceType, ok := types[goName]
		if !ok {
			return nil, fmt.Errorf("required type %s is missing", goName)
		}
		if values := constants[goName]; len(values) > 0 {
			writeStringUnion(&out, outputNames[goName], values)
			continue
		}
		if union := unionMembers(sourceType.doc); len(union) > 0 {
			writeNamedUnion(&out, outputNames[goName], union)
			continue
		}
		structure, ok := sourceType.expr.(*ast.StructType)
		if !ok {
			return nil, fmt.Errorf("type %s is neither a string enum, struct, nor wire:union", goName)
		}
		if err := writeStruct(&out, outputNames[goName], structure); err != nil {
			return nil, fmt.Errorf("type %s: %w", goName, err)
		}
	}
	return bytes.TrimSuffix(out.Bytes(), []byte("\n")), nil
}

func writeStringUnion(out *bytes.Buffer, name string, values []string) {
	if len(values) == 1 {
		fmt.Fprintf(out, "export type %s = %s\n\n", name, strconv.Quote(values[0]))
		return
	}
	fmt.Fprintf(out, "export type %s =\n", name)
	for _, value := range values {
		fmt.Fprintf(out, "  | %s\n", strconv.Quote(value))
	}
	out.WriteByte('\n')
}

func writeNamedUnion(out *bytes.Buffer, name string, members []string) {
	fmt.Fprintf(out, "export type %s = %s\n\n", name, strings.Join(mappedNames(members), " | "))
}

func writeStruct(out *bytes.Buffer, name string, structure *ast.StructType) error {
	fmt.Fprintf(out, "export type %s = {\n", name)
	for _, field := range structure.Fields.List {
		if len(field.Names) != 1 || field.Tag == nil {
			return fmt.Errorf("all fields must be named and have a JSON tag")
		}
		tagLiteral, err := strconv.Unquote(field.Tag.Value)
		if err != nil {
			return err
		}
		jsonTag := reflect.StructTag(tagLiteral).Get("json")
		parts := strings.Split(jsonTag, ",")
		if parts[0] == "-" {
			continue
		}
		if parts[0] == "" {
			return fmt.Errorf("field %s has an empty JSON name", field.Names[0].Name)
		}
		optional := ""
		if len(parts) > 1 && slicesContain(parts[1:], "omitempty") {
			optional = "?"
		}
		tsType, err := translateType(field.Type)
		if err != nil {
			return fmt.Errorf("field %s: %w", field.Names[0].Name, err)
		}
		fmt.Fprintf(out, "  %s%s: %s\n", parts[0], optional, tsType)
	}
	out.WriteString("}\n\n")
	return nil
}

func translateType(expr ast.Expr) (string, error) {
	switch value := expr.(type) {
	case *ast.Ident:
		switch value.Name {
		case "string":
			return "string", nil
		case "int", "int64", "uint64", "float64":
			return "number", nil
		case "bool":
			return "boolean", nil
		case "any":
			return "unknown", nil
		default:
			name, ok := outputNames[value.Name]
			if !ok {
				return "", fmt.Errorf("unsupported named type %s", value.Name)
			}
			return name, nil
		}
	case *ast.ArrayType:
		element, err := translateType(value.Elt)
		if err != nil {
			return "", err
		}
		return element + "[]", nil
	case *ast.StarExpr:
		return translateType(value.X)
	default:
		return "", fmt.Errorf("unsupported Go expression %T", expr)
	}
}

func unionMembers(doc string) []string {
	for _, line := range strings.Split(doc, "\n") {
		if rest, ok := strings.CutPrefix(strings.TrimSpace(line), "wire:union "); ok {
			return strings.Fields(rest)
		}
	}
	return nil
}

func mappedNames(names []string) []string {
	out := make([]string, len(names))
	for index, name := range names {
		out[index] = outputNames[name]
	}
	return out
}

func commentText(group *ast.CommentGroup) string {
	if group == nil {
		return ""
	}
	return group.Text()
}

func slicesContain(values []string, wanted string) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}
