package skills

import (
	"context"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/ktsoator/or/agent"
	"github.com/ktsoator/or/llm"
)

// ToolName is the advertised name of the skill-loading tool.
const ToolName = "skill"

const toolDescription = "Load a skill's full instructions on demand. Product context announces the " +
	"available skills by name and description; when the current task matches one, call this tool " +
	"with that skill's name BEFORE acting, then follow the instructions it returns. Only names from " +
	"the listing are valid — never guess."

const relativePathProtocol = "Resolve every relative path in this skill against the skill root above. " +
	"Use the resolved absolute path when calling tools."

const explicitInvocationPrefix = "<agent-skill-invocation "

type skillCallArgs struct {
	Name string `json:"name" jsonschema:"description=Name of the skill to load, exactly as shown in the available skills listing,minLength=1"`
}

// Tool returns the agent tool that loads a skill's body on demand. The returned
// tool only reads registered skills; it makes no workspace changes, so callers
// should advertise it as read-only. On an unknown name it returns an error
// naming the valid skills, so the model corrects rather than guesses.
func (r *Registry) Tool() agent.AgentTool {
	return newTool(r.Lookup, r.names)
}

// newTool builds the stable skill-tool schema around snapshot-aware lookup
// functions. Registry and DynamicRegistry share this implementation so changing
// the active registry never changes the provider-visible tool definition.
func newTool(
	lookup func(string) (Skill, bool),
	names func() []string,
) agent.AgentTool {
	return agent.AgentTool{
		Definition: llm.MustTool[skillCallArgs](ToolName, toolDescription),
		Label:      "Skill",
		Execute: func(_ context.Context, _ string, raw json.RawMessage, _ func(agent.ToolProgress)) (agent.ToolResult, error) {
			var in skillCallArgs
			if err := json.Unmarshal(raw, &in); err != nil {
				return agent.ToolResult{}, err
			}
			name := strings.TrimSpace(in.Name)
			s, ok := lookup(name)
			if !ok {
				msg := unknownSkillMessage(name, names())
				return failedTextResult("skill_not_found", msg), fmt.Errorf("%s", msg)
			}
			return textResult(formatLoadedSkill(s)), nil
		},
	}
}

// formatLoadedSkill renders a skill's body unchanged as the tool result the
// model reads, wrapped so the instruction boundary and skill root are explicit.
func formatLoadedSkill(s Skill) string {
	return fmt.Sprintf(
		"<loaded_skill name=%q root=%q>\n%s\n\n%s\n</loaded_skill>\n\nFollow the loaded skill instructions for the current task.",
		s.Name,
		s.Dir,
		relativePathProtocol,
		s.Content,
	)
}

// ResolveExplicitInvocation recognizes a leading $skill-name mention or a
// product-generated SKILL.md reference and resolves it against the registry.
// The returned block follows the visible user text in the same message.
func (r *Registry) ResolveExplicitInvocation(text string) (loaded string, matched bool, err error) {
	name, arguments, matched := parseExplicitInvocation(text)
	if !matched {
		return "", false, nil
	}
	s, ok := r.Lookup(name)
	if !ok {
		msg := unknownSkillMessage(name, r.names())
		return "", true, fmt.Errorf("%s", msg)
	}
	return fmt.Sprintf(
		"%sname=%q root=%q>\n"+
			"The user explicitly invoked this skill. It is already loaded; do not call the skill tool again.\n"+
			"The user's task details remain in the visible message: %q.\n"+
			"%s\n\n%s\n"+
			"</agent-skill-invocation>",
		explicitInvocationPrefix,
		s.Name,
		s.Dir,
		arguments,
		relativePathProtocol,
		s.Content,
	), true, nil
}

// IsExplicitInvocationText reports whether a text block was generated by
// ResolveExplicitInvocation. UI/history projections omit these blocks.
func IsExplicitInvocationText(text string) bool {
	return strings.HasPrefix(text, explicitInvocationPrefix)
}

// DisplayExplicitInvocation converts an explicit invocation into a durable
// Markdown reference to its SKILL.md file. The UI can render the reference as a
// rich token while copying it remains useful plain text.
func (r *Registry) DisplayExplicitInvocation(text string) string {
	name, arguments, matched := parseExplicitInvocation(text)
	if !matched || name == "" {
		return text
	}
	skill, ok := r.Lookup(name)
	if !ok {
		return text
	}
	path := skill.Path
	if path == "" && skill.Dir != "" {
		path = filepath.Join(skill.Dir, skillFile)
	}
	destination := path
	if strings.ContainsAny(destination, " \t\r\n()") {
		destination = "<" + strings.ReplaceAll(destination, ">", "%3E") + ">"
	}
	reference := fmt.Sprintf("[$%s](%s)", name, destination)
	if arguments == "" {
		return reference
	}
	return reference + " " + arguments
}

func parseExplicitInvocation(text string) (name, arguments string, matched bool) {
	trimmed := strings.TrimSpace(text)
	if name, arguments, matched := parseSkillReference(trimmed); matched {
		return name, arguments, true
	}
	if !strings.HasPrefix(trimmed, "$") {
		return "", "", false
	}
	rest := strings.TrimPrefix(trimmed, "$")
	if rest == "" {
		return "", "", false
	}
	if split := strings.IndexFunc(rest, func(r rune) bool {
		return r == ' ' || r == '\t' || r == '\r' || r == '\n'
	}); split >= 0 {
		name := rest[:split]
		return name, strings.TrimSpace(rest[split:]), name != ""
	}
	return rest, "", true
}

func parseSkillReference(text string) (name, arguments string, matched bool) {
	if !strings.HasPrefix(text, "[$") {
		return "", "", false
	}
	labelEnd := strings.Index(text, "](")
	if labelEnd < 2 {
		return "", "", false
	}
	name = text[2:labelEnd]
	rest := text[labelEnd+2:]
	var destinationEnd int
	if strings.HasPrefix(rest, "<") {
		destinationEnd = strings.Index(rest, ">)")
		if destinationEnd < 1 {
			return "", "", false
		}
		destinationEnd++
	} else {
		destinationEnd = strings.Index(rest, ")")
		if destinationEnd < 0 {
			return "", "", false
		}
	}
	after := rest[destinationEnd+1:]
	return name, strings.TrimSpace(after), name != ""
}

// unknownSkillMessage explains an unknown skill name and lists the valid ones.
func unknownSkillMessage(name string, valid []string) string {
	if len(valid) == 0 {
		return fmt.Sprintf("Unknown skill %q: no skills are available.", name)
	}
	return fmt.Sprintf("Unknown skill %q. Available skills: %s.", name, strings.Join(valid, ", "))
}

// textResult builds a ToolResult carrying a single text block.
func textResult(text string) agent.ToolResult {
	return agent.ToolResult{
		Content: []llm.ToolResultContent{&llm.TextContent{Text: text}},
		Outcome: agent.ToolOutcome{Status: agent.ToolOutcomeSuccess},
	}
}

func failedTextResult(code, text string) agent.ToolResult {
	return agent.ToolResult{
		Content: []llm.ToolResultContent{&llm.TextContent{Text: text}},
		Outcome: agent.ToolOutcome{Status: agent.ToolOutcomeFailed, ErrorCode: code},
	}
}
